version: '3.3'

services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'pg123456'
      POSTGRES_DB: 'tinder_step'
    ports:
      - '5432:5432'

    volumes:
      - ./pgfiles:/var/lib/postgresql/data
    container_name: pg_0
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: test@test.com
      PGADMIN_DEFAULT_PASSWORD: test
  app:
    restart: unless-stopped
    build: .
    environment:
      JDBC_DATABASE_URL : "jdbc:postgresql://postgres:5432/tinder_step"
      JDBC_DATABASE_LOGIN : "postgres"
      JDBC_DATABASE_PASSWORD : "pg123456"
    ports:
      - '8080:8080'
    container_name: app
    depends_on:
      - postgres
#networks:
#  dev-network:
#    external: false
#    name: dev-network
#
#
