INSERT INTO users (name,url,pwd) VALUES ('Anna','https://images.unsplash.com/photo-1524504388940-b1c1722653e1','qwerty');
insert into users (name,url,pwd) values ('Mila','https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e','qwerty');
insert into users (name,url,pwd) values ('Rosa','https://images.unsplash.com/photo-1494790108377-be9c29b29330','qwerty');
insert into users (name,url,pwd) values ('Angela','https://images.unsplash.com/photo-1583766395091-2eb9994ed094','qwerty');
insert into users (name,url,pwd) values ('Monica','https://images.unsplash.com/photo-1517841905240-472988babdf9','qwerty');
insert into users (name,url,pwd) values ('Liza','https://images.unsplash.com/photo-1488426862026-3ee34a7d66df','qwerty');
insert into users (name,url,pwd) values ('Anton','https://images.unsplash.com/photo-1539571696357-5a69c17a67c6','qwerty');