UPDATE public.users SET
    email = 'sensor@s'::character varying WHERE
    id = 3;
UPDATE public.users SET
    email = 'test@test'::character varying WHERE
    id = 1;
UPDATE public.users SET
    email = 't@t'::character varying WHERE
    id = 2;
UPDATE public.users SET
    email = 'admin@a'::character varying WHERE
    id = 4;
UPDATE public.users SET
    email = 'a@a'::character varying WHERE
    id = 5;
UPDATE public.users SET
    email = 'keona_fort@hierarchy.xil'::character varying WHERE
    id = 6;
UPDATE public.users SET
    email = 'kelina_lichngd@census.cq'::character varying WHERE
    id = 7;
UPDATE public.users SET
    email = 'zalmenwov@a'::character varying WHERE
    id = 8;